Create survey.md
digital-sustainability/civil42 pull request #6
Opened 2024-03-12 08:45 UTC by MarkusTiede

- [x] Digitale Souveränität: Bekannt, Relevant, Existent?
 - [x] 2. Seite aufteilen auf: Impact & Bedarf

2024-03-13 07:27 UTC, olibrian requested changes
Habe erste Rückmeldungen

2024-03-13 07:27 UTC, olibrian commented on docs/survey.md
> +Die Umfrage wird im Rahmen eines Innosuisse Innovationsscheck Projektes "[civil42](https://github.com/digital-sustainability/civil42)" von der Berner Fachhochschule sowie der Firma [Puzzle ITC](https
Bist du sicher, dass du hier unser Arbeitsrepo referenzieren willst?

2024-03-13 07:27 UTC, olibrian commented on docs/survey.md
> +#### Frage 1.1: Name / Webseite des Vereins
Ev Mailadresse, falls die Person an dem Ergebnis interessiert ist

2024-03-13 07:27 UTC, olibrian commented on docs/survey.md
> +#### Frage 2.3: Wo besteht der grösste Bedarf an einem (digitalen, automatisierten) Prozess bzw. Software?
Das Wort Bedarf löst bei mir sofort etwas Markteting mässig aus. Auf einen Bedarf folgt gleich ein Angebot :-)
Wie wäre es mit Handlungsbedarf?

2024-03-13 07:27 UTC, olibrian commented on docs/survey.md
> +#### Frage 3.2: Kontakt bei Abschluss?
Ist hier der Kontakt zur BFH gemeint? Fände ich gut.

2024-03-13 07:50 UTC, MarkusTiede commented on docs/survey.md
> +Die Umfrage wird im Rahmen eines Innosuisse Innovationsscheck Projektes "[civil42](https://github.com/digital-sustainability/civil42)" von der Berner Fachhochschule sowie der Firma [Puzzle ITC](https
ggfs. besser: https://digital-sustainability.github.io/civil42/

2024-03-19 08:33 UTC, MarkusTiede commented
# Sounding-Board im Vereins-Circle
- @Kateschuetz (CH Open) & [Kristelle Plüss](https://www.bfh.ch/de/kristelle-pluess) (Parldigi)
- @jonasbaertschi (Swiss Data Alliance) & [Melanie Eva Noser](https://www.bfh.ch/de/melanie-eva-noser) (Digital Impact Network)

2024-03-21 08:09 UTC, MarkusTiede commented
## @jonasbaertschi (Swiss Data Alliance) & [Melanie Eva Noser](https://www.bfh.ch/de/melanie-eva-noser) (Digital Impact Network)

- Frage 2: Inwiefern ist das Konzept bekannt?
 > Besser: Aussage («Das Konzept ist in unserem Verein sehr bekannt») und dann Bewertung («Trifft voll zu», «trifft nicht zu»)

- «Angewandt und gelebt» ist für mich nicht so fassbar

- Grad der Digitalisierung: Das IPST hat ein Maturitätsmodell für Digitalisierung erarbeitet, auf das man hier verweisen könnte: https://www.bfh.ch/dam/jcr:bc9f0aa2-cdfa-43d5-81b4-f1c7025ed23b/20230605_eGov-Sommer-Feiner-APP-Digitale-Skills.pdf (Folie 10)

- «Impact von (digitalen) Tools» ist nicht so fassbar. Vielleicht eher: «Welches digitale Tool würde die grösste Lücke hinterlassen, wenn es nicht mehr verfügbar wäre?»

 - Was ist mit «Handlungsbedarf» gemeint?

2024-03-22 09:05 UTC, MarkusTiede commented
[Digitale Souveränität von Vereinen(ID:134196)](https://surveys.bfh.ch/index.php/admin/survey/sa/view/surveyid/134196)

2024-04-09 08:32 UTC, MarkusTiede commented
# öffentlicher Link: https://surveys.bfh.ch/index.php/134196?lang=de

2024-04-10 08:17 UTC, olibrian approved these changes

2024-04-10 08:18 UTC, olibrian approved these changes
Denke dies passt so.

2024-04-10 08:18 UTC, merged